### PR TITLE
df says it is 126mb.

### PR DESCRIPTION
**Pull request by lgrootnoob**
another fassy user says it is 128mb.(with diskinfo)
im too lazy to look at the proper way to calculate this on the cm docs. so here bruh

Filesystem               Size     Used     Free   Blksize
/dev                   208.2M   136.0K   208.1M   4096
/sys/fs/cgroup         208.2M     0.0K   208.2M   4096
/mnt/asec              208.2M     0.0K   208.2M   4096
/mnt/obb               208.2M     0.0K   208.2M   4096
/mnt/fuse              208.2M     0.0K   208.2M   4096
/datadata              468.0M    89.2M   378.8M   4096
/system                590.6M   310.9M   279.7M   4096
/data                    1.1G   477.9M   671.6M   4096
/data/data             468.0M    89.2M   378.8M   4096
/cache                 126.0M     4.3M   121.7M   4096
/mnt/media_rw/sdcard0    59.6G    39.7G    19.9G   131072
/storage/sdcard0        59.6G    39.7G    19.9G   131072

major minor  #blocks  name

  31        0       7680 mtdblock0
  31        1       7680 mtdblock1
  31        2     479232 mtdblock2
  31        3      11264 mtdblock3
 253        0     147456 zram0
 179        0    1953792 mmcblk0
 179        1    1626104 mmcblk0p1
 179        2     196608 mmcblk0p2
 179        3     131072 mmcblk0p3
 179        8   62521344 mmcblk1
 179        9   62504960 mmcblk1p1
 254        0     614400 dm-0
 254        1    1196032 dm-1

rootfs / rootfs ro,seclabel,relatime 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
none /dev/cpuctl cgroup rw,relatime,cpu 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
none /sys/fs/cgroup tmpfs rw,seclabel,relatime,mode=750,gid=1000 0 0
none /sys/fs/cgroup/memory cgroup rw,relatime,memory 0 0
/sys/kernel/debug /sys/kernel/debug debugfs rw,relatime 0 0
none /acct cgroup rw,relatime,cpuacct 0 0
tmpfs /mnt/asec tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/obb tmpfs rw,seclabel,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/fuse tmpfs rw,seclabel,relatime,mode=775,gid=1000 0 0
/dev/block/mtdblock2 /datadata yaffs2 rw,seclabel,relatime 0 0
/dev/lvpool/system /system ext4 ro,seclabel,relatime,user_xattr,barrier=1,data=ordered 0 0
/dev/lvpool/userdata /data ext4 rw,seclabel,nosuid,nodev,noatime,errors=panic,user_xattr,barrier=1,nomblk_io_submit,data=ordered 0 0
/dev/block/mtdblock2 /data/data yaffs2 rw,seclabel,relatime 0 0
/dev/block/mmcblk0p3 /cache ext4 rw,seclabel,nosuid,nodev,noatime,errors=panic,user_xattr,barrier=1,nomblk_io_submit,data=ordered 0 0
/dev/block/vold/179:9 /mnt/media_rw/sdcard0 fuseblk rw,dirsync,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other,blksize=4096 0 0
/dev/fuse /storage/sdcard0 fuse rw,nosuid,nodev,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0

### CODE REVIEW

**Comment by xc-racer99** [comment]
Honestly, it doesn't really matter, so much so that CM even removed the warning.  However, I'll merge this is its more "correct"

I'm assuming you want a new test Fascinate build?  I think I figured out what I was doing wrong...

**Comment by lgrootnoob** [comment]
A new test build would be much appreciated :D I even synced all the sources for 6.0 so ye

**Comment by xc-racer99** [comment]
Well then you could build it yourself and tell me if it works :) - I hate having to upload full builds on my slow internet connection...

**Comment by xc-racer99** [comment]
Just let me upload my changes which should make things bootable...

**Pull request merged**
